server:
  port: 8083
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Dynamic-Form-Generation
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

